config/routes.rb
Rails.application.routes.draw do
  resources :employments
  resources :scheduled_appointments
  resources :schedules
  resources :doctor_shifts
  resources :hospitals
  root to: 'home#index' 
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  resources :admins, :path => 'users'
  resources :doctors, :path => 'users'
  resources :patients, :path => 'users'

  get 'bookings', to: 'bookings#index'
  get 'bookings/mine', to: 'bookings#show'
  post 'bookings', to: 'bookings#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employment.rb
class Employment < ApplicationRecord
    belongs_to :doctor
    belongs_to :hospital
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: [:show, :edit, :update, :destroy]

  # GET /employments
  # GET /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1
  # GET /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments
  # POST /employments.json
  def create
    @employment = Employment.new(employment_params)

    respond_to do |format|
      if @employment.save
        format.html { redirect_to @employment, notice: 'Employment was successfully created.' }
        format.json { render :show, status: :created, location: @employment }
      else
        format.html { render :new }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1
  # PATCH/PUT /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to @employment, notice: 'Employment was successfully updated.' }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1
  # DELETE /employments/1.json
  def destroy
    @employment.destroy
    respond_to do |format|
      format.html { redirect_to employments_url, notice: 'Employment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employment_params
      params.require(:employment).permit(:doctor_id, :hospital_id)
    end
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employments/_form.html.erb
<%= form_with(model: employment, local: true) do |form| %>
  <% if employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employment.errors.count, "error") %> prohibited this employment from being saved:</h2>

      <ul>
        <% employment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if employment.doctor == nil %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <% doctor_array = Doctor.all.select{|d| d.hospital == nil}.map{|d| [d.name, d.id]} %>
      <%= form.select :doctor_id, options_for_select(doctor_array), {}, {class: 'custom-select', style:'width:200px;display:inherit;'} %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <div class="form-control"><%= employment.doctor.name %></div>
      <% form.hidden_field :doctor_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :hospital_id %>
    <% hospital_array = Hospital.all.map{|h| [h.name, h.id]} %>
    <% hospital_selected = employment.hospital != nil ? employment.hospital.id : nil %>
    <%= form.select :hospital_id, options_for_select(hospital_array, hospital_selected), {}, {class: 'custom-select', style:'width:200px;display:inherit;'} %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mb-2' %>
  </div>
<% end %>

app/views/employments/edit.html.erb
<h1>Editing Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Show', @employment %> |
<%= link_to 'Back', employments_path %>

app/views/employments/index.html.erb
<h1>Employments</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Doctor Name</th>
      <th scope="col">Hospital Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employments.each do |employment| %>
      <tr>
        <td><%= employment.doctor.name %></td>
        <td><%= employment.hospital.name %></td>
        <td><%= link_to 'Show', employment %></td>
        <td><%= link_to 'Edit', edit_employment_path(employment) %></td>
        <td><%= link_to 'Destroy', employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment', new_employment_path %>

app/views/employments/new.html.erb
<h1>New Employment</h1>

<%= render 'form', employment: @employment %>

<%= link_to 'Back', employments_path, class: 'btn btn-secondary'  %>

app/views/employments/show.html.erb
<p>
  <strong>Doctor:</strong>
  <%= @employment.doctor.name %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @employment.hospital.name %>
</p>

<%= link_to 'Edit', edit_employment_path(@employment) %> |
<%= link_to 'Back', employments_path %>