config/routes.rb
Rails.application.routes.draw do
  resources :employments
  resources :scheduled_appointments
  resources :schedules
  resources :doctor_shifts
  resources :hospitals
  root to: 'home#index' 
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  resources :admins, :path => 'users'
  resources :doctors, :path => 'users'
  resources :patients, :path => 'users'

  get 'bookings', to: 'bookings#index'
  get 'bookings/mine', to: 'bookings#show'
  post 'bookings', to: 'bookings#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/scheduled_appointment.rb
class ScheduledAppointment < ApplicationRecord
  belongs_to :schedule
  belongs_to :patient
  belongs_to :doctor
end

app/controllers/scheduled_appointments_controller.rb
class ScheduledAppointmentsController < ApplicationController
  before_action :set_scheduled_appointment, only: [:show, :edit, :update, :destroy]

  # GET /scheduled_appointments
  # GET /scheduled_appointments.json
  def index
    @scheduled_appointments = ScheduledAppointment.all
  end

  # GET /scheduled_appointments/1
  # GET /scheduled_appointments/1.json
  def show
  end

  # GET /scheduled_appointments/new
  def new
    @scheduled_appointment = ScheduledAppointment.new
  end

  # GET /scheduled_appointments/1/edit
  def edit
  end

  # POST /scheduled_appointments
  # POST /scheduled_appointments.json
  def create
    @scheduled_appointment = ScheduledAppointment.new(scheduled_appointment_params)

    respond_to do |format|
      if @scheduled_appointment.save
        format.html { redirect_to @scheduled_appointment, notice: 'Scheduled appointment was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled_appointment }
      else
        format.html { render :new }
        format.json { render json: @scheduled_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_appointments/1
  # PATCH/PUT /scheduled_appointments/1.json
  def update
    respond_to do |format|
      if @scheduled_appointment.update(scheduled_appointment_params)
        format.html { redirect_to @scheduled_appointment, notice: 'Scheduled appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_appointment }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_appointments/1
  # DELETE /scheduled_appointments/1.json
  def destroy
    @scheduled_appointment.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_appointments_url, notice: 'Scheduled appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_appointment
      @scheduled_appointment = ScheduledAppointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def scheduled_appointment_params
      params.require(:scheduled_appointment).permit(:schedule_id, :doctor_id, :patient_id)
    end
end

app/helpers/scheduled_appointments_helper.rb
module ScheduledAppointmentsHelper
end

app/views/scheduled_appointments/_form.html.erb
<%= form_with(model: scheduled_appointment, local: true) do |form| %>
  <% if scheduled_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduled_appointment.errors.count, "error") %> prohibited this scheduled_appointment from being saved:</h2>

      <ul>
        <% scheduled_appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if scheduled_appointment.schedule_id == nil %>
    <div class="form-group">
      <%= form.label :schedule_id %>
      <% schedule_array = Schedule.all.map{|s| ["#{s.start_time.strftime('%D %T')} - #{s.end_time.strftime('%D %T')} (#{s.doctor.name})", s.id]} %>
      <%= form.select :schedule_id, options_for_select(schedule_array), {}, {class: 'custom-select', style:'width:800px;display:inherit;'} %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :schedule_id %>
      <div class="form-control"><%= "#{scheduled_appointment.schedule.start_time.strftime('%D %T')}-#{scheduled_appointment.schedule.end_time.strftime('%D %T')}" %></div>
      <% form.hidden_field :schedule_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :patient_id %>
    <% patient_array = Patient.all.map{|d| [d.name, d.id]} %>
    <%= form.select :patient_id, options_for_select(patient_array), {}, {class: 'custom-select', style:'width:200px;display:inherit;'} %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mb-2' %>
  </div>
<% end %>

app/views/scheduled_appointments/edit.html.erb
<h1>Editing Scheduled Appointment</h1>

<%= render 'form', scheduled_appointment: @scheduled_appointment %>

<%= link_to 'Show', @scheduled_appointment %> |
<%= link_to 'Back', scheduled_appointments_path %>

app/views/scheduled_appointments/index.html.erb
<h1>Scheduled Appointments</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="colspan">Schedule</th>
      <th scope="colspan">Doctor</th>
      <th scope="colspan">Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_appointments.each do |scheduled_appointment| %>
      <tr>
        <td><%= scheduled_appointment.schedule.start_time.strftime('%D %T') %> - <%= scheduled_appointment.schedule.end_time.strftime('%D %T') %></td>
        <td><%= scheduled_appointment.schedule.doctor.name %></td>
        <td><%= scheduled_appointment.patient.name %></td>
        <td><%= link_to 'Show', scheduled_appointment %></td>
        <td><%= link_to 'Edit', edit_scheduled_appointment_path(scheduled_appointment) %></td>
        <td><%= link_to 'Destroy', scheduled_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduled Appointment', new_scheduled_appointment_path %>

app/views/scheduled_appointments/new.html.erb
<h1>New Scheduled Appointment</h1>

<%= render 'form', scheduled_appointment: @scheduled_appointment %>

<%= link_to 'Back', scheduled_appointments_path, class: 'btn btn-secondary'  %>

app/views/scheduled_appointments/show.html.erb
<p>
  <strong>Schedule:</strong>
  <%= @scheduled_appointment.schedule.start_time.strftime('%D %T') %> - <%= @scheduled_appointment.schedule.end_time.strftime('%D %T') %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @scheduled_appointment.schedule.doctor.name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @scheduled_appointment.patient.name %>
</p>

<%= link_to 'Edit', edit_scheduled_appointment_path(@scheduled_appointment) %> |
<%= link_to 'Back', scheduled_appointments_path %>