config/routes.rb
Rails.application.routes.draw do
  resources :employments
  resources :scheduled_appointments
  resources :schedules
  resources :doctor_shifts
  resources :hospitals
  root to: 'home#index' 
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  resources :admins, :path => 'users'
  resources :doctors, :path => 'users'
  resources :patients, :path => 'users'

  get 'bookings', to: 'bookings#index'
  get 'bookings/mine', to: 'bookings#show'
  post 'bookings', to: 'bookings#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :doctor
  has_many :scheduled_appointments
  has_many :patients, through: :scheduled_appointments

  def self.from_shift(datetime, doctor_shift)
    date_fmt = datetime.beginning_of_day
    start_time_seconds = doctor_shift.start_hour * 3600 + doctor_shift.start_min * 60
    end_time_seconds = doctor_shift.end_hour * 3600 + doctor_shift.end_min * 60
    start_time = date_fmt + start_time_seconds.seconds
    end_time = date_fmt + end_time_seconds.seconds
    doctor_id = doctor_shift.doctor_id
    Schedule.where(doctor_id: doctor_id, start_time: start_time, end_time: end_time).first_or_create
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:doctor_id, :start_time, :end_time)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if schedule.doctor == nil %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <% doctor_array = Doctor.all.map{|d| [d.name, d.id]} %>
      <%= form.select :doctor_id, options_for_select(doctor_array), {}, {class: 'custom-select', style:'width:200px;display:inherit;'} %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <div class="form-control"><%= schedule.doctor.name %></div>
      <% form.hidden_field :doctor_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btm-submit mb-2' %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Doctor</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.doctor.name %></td>
        <td><%= schedule.start_time.strftime('%D %T') %></td>
        <td><%= schedule.end_time.strftime('%D %T') %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path, class: 'btn btn-secondary'  %>

app/views/schedules/show.html.erb
<p>
  <strong>Doctor:</strong>
  <%= @schedule.doctor_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @schedule.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @schedule.end_time %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>