config/routes.rb
Rails.application.routes.draw do
  resources :employments
  resources :scheduled_appointments
  resources :schedules
  resources :doctor_shifts
  resources :hospitals
  root to: 'home#index' 
  devise_for :users, controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  resources :admins, :path => 'users'
  resources :doctors, :path => 'users'
  resources :patients, :path => 'users'

  get 'bookings', to: 'bookings#index'
  get 'bookings/mine', to: 'bookings#show'
  post 'bookings', to: 'bookings#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor_shift.rb
class DoctorShift < ApplicationRecord
  belongs_to :doctor
end

app/controllers/doctor_shifts_controller.rb
class DoctorShiftsController < ApplicationController
  before_action :set_doctor_shift, only: [:show, :edit, :update, :destroy]

  # GET /doctor_shifts
  # GET /doctor_shifts.json
  def index
    @doctor_shifts = DoctorShift.all
  end

  # GET /doctor_shifts/1
  # GET /doctor_shifts/1.json
  def show
  end

  # GET /doctor_shifts/new
  def new
    @doctor_shift = DoctorShift.new
  end

  # GET /doctor_shifts/1/edit
  def edit
  end

  # POST /doctor_shifts
  # POST /doctor_shifts.json
  def create
    @doctor_shift = DoctorShift.new(doctor_shift_params)

    respond_to do |format|
      if @doctor_shift.save
        format.html { redirect_to @doctor_shift, notice: 'Doctor shift was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_shift }
      else
        format.html { render :new }
        format.json { render json: @doctor_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_shifts/1
  # PATCH/PUT /doctor_shifts/1.json
  def update
    respond_to do |format|
      if @doctor_shift.update(doctor_shift_params)
        format.html { redirect_to @doctor_shift, notice: 'Doctor shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_shift }
      else
        format.html { render :edit }
        format.json { render json: @doctor_shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_shifts/1
  # DELETE /doctor_shifts/1.json
  def destroy
    @doctor_shift.destroy
    respond_to do |format|
      format.html { redirect_to doctor_shifts_url, notice: 'Doctor shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_shift
      @doctor_shift = DoctorShift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_shift_params
      params.require(:doctor_shift).permit(:doctor_id, :start_hour, :start_min, :end_hour, :end_min)
    end
end

app/helpers/doctor_shifts_helper.rb
module DoctorShiftsHelper
end

app/views/doctor_shifts/_form.html.erb
<%= form_with(model: doctor_shift, local: true) do |form| %>
  <% if doctor_shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor_shift.errors.count, "error") %> prohibited this doctor_shift from being saved:</h2>

      <ul>
        <% doctor_shift.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if doctor_shift.doctor == nil %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <% doctor_array = Doctor.all.map{|d| [d.name, d.id]} %>
      <%= form.select :doctor_id, options_for_select(doctor_array), {}, {class: 'custom-select', style:'width:200px;display:inherit;'} %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :doctor_id %>
      <div class="form-control"><%= doctor_shift.doctor.name %></div>
      <% form.hidden_field :doctor_id %>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :start_hour %>
      <%= form.number_field :start_hour, max: 23, min: 0, placeholder: 'Start Hour', class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :start_min %>
      <%= form.number_field :start_min, max: 59, min: 0, placeholder: 'Start Minutes', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <%= form.label :end_hour %>
      <%= form.number_field :end_hour, max: 23, min: 0, placeholder: 'End Hour', class: 'form-control' %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :end_min %>
      <%= form.number_field :end_min, max: 59, min: 0, placeholder: 'End Minutes', class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary mb-2' %>
  </div>
<% end %>

app/views/doctor_shifts/edit.html.erb
<h1>Editing Doctor Shift</h1>

<%= render 'form', doctor_shift: @doctor_shift %>

<%= link_to 'Show', @doctor_shift %> |
<%= link_to 'Back', doctor_shifts_path %>

app/views/doctor_shifts/index.html.erb
<h1>Doctor Shifts</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Doctor</th>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctor_shifts.each do |doctor_shift| %>
      <tr>
        <td><%= doctor_shift.doctor.name %></td>
        <td><%= doctor_shift.start_hour.to_s.rjust(2,'0') %>:<%= doctor_shift.start_min.to_s.rjust(2,'0') %></td>
        <td><%= doctor_shift.end_hour.to_s.rjust(2,'0') %>:<%= doctor_shift.end_min.to_s.rjust(2,'0') %></td>
        <td><%= link_to 'Show', doctor_shift %></td>
        <td><%= link_to 'Edit', edit_doctor_shift_path(doctor_shift) %></td>
        <td><%= link_to 'Destroy', doctor_shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor Shift', new_doctor_shift_path %>

app/views/doctor_shifts/new.html.erb
<h1>New Doctor Shift</h1>

<%= render 'form', doctor_shift: @doctor_shift %>

<%= link_to 'Back', doctor_shifts_path, class: 'btn btn-secondary'  %>

app/views/doctor_shifts/show.html.erb
<p>
  <strong>Doctor:</strong>
  <%= @doctor_shift.doctor.name %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @doctor_shift.start_hour.to_s.rjust(2,'0') %>:<%= @doctor_shift.start_min.to_s.rjust(2,'0') %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @doctor_shift.end_hour.to_s.rjust(2,'0') %>:<%= @doctor_shift.end_min.to_s.rjust(2,'0') %>
</p>

<%= link_to 'Edit', edit_doctor_shift_path(@doctor_shift) %> |
<%= link_to 'Back', doctor_shifts_path %>